#!/bin/sh

session=${1:-tmux}
colors="#f97316 #fb923c #fdba74 #fb923c"
second=$(date +%S)
idx=$((10#$second % 4))
set -- $colors
color="#f97316"
case "$idx" in
  0) color="$1" ;;
  1) color="$2" ;;
  2) color="$3" ;;
  3) color="$4" ;;
esac
printf '#[fg=%s]#[bold] COMMAND #[fg=#403f53]#[bold]%s ' "$color" "$session"
